version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - appnet

  webapp:
    build:
      context: .
      dockerfile: webapp/Dockerfile
    environment:
      - VITE_API_BASE=http://backend:8000
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
